package kiryasay.springmvc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class DBWorker {

       static String url = "jdbc:postgresql://localhost:5432/ParalelDB";
       static String user= "postgres";
        static String password = "kiryasay";

    public DBWorker()
    {

    }

    static void createClientTable()
    {
        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            String create = "CREATE TABLE client(\n" +
                    "    id int GENERATED BY DEFAULT AS IDENTITY,\n" +
                    "    name varchar,\n" +
                    "    phone varchar,\n" +
                    "    address varchar,\n" +
                    "    account_number varchar\n" +
                    "\n" +
                    ");";

            PreparedStatement preparedStatement = connection.prepareStatement(create);
            preparedStatement.executeUpdate();
        }
        catch (SQLException e){
            e.printStackTrace();
        }
    }

    static void deleteClientTable()
    {
        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            String create = "DROP TABLE client";

            PreparedStatement preparedStatement = connection.prepareStatement(create);
            preparedStatement.executeUpdate();
        }
        catch (SQLException e){
            e.printStackTrace();
        }
    }
}
